- extensions/2.0/Vendor/EXT_feature_metadata/schema/class.property.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/featureIdAttribute.featureIds.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/gltf.EXT_feature_metadata.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/statistics.class.property.schema.json
Includes @kring's commits from https://github.com/CesiumGS/glTF/pull/6 but rebased onto `3d-tiles-next` where the folder structure changed (see https://github.com/CesiumGS/glTF/pull/9#issuecomment-908769685 for details)
> EXT_feature_metadata JSON schema cleanup

- extensions/2.0/Vendor/EXT_feature_metadata/README.md
- extensions/2.0/Vendor/EXT_feature_metadata/schema/featureIdAttribute.featureIds.schema.json
From https://github.com/CesiumGS/glTF/pull/9 –
- Refine binary data storage to avoid breaking changes to upstream glTF 2.0
- Remove prefix: `_FEATURE_ID_#` → `FEATURE_ID_#`
- Define ID and NAME semantics directly in the document
> Updates to EXT_feature_metadata

- extensions/2.0/Vendor/EXT_feature_metadata/schema/class.property.schema.json
Implements option (E) from https://github.com/CesiumGS/3d-tiles-next/issues/152, which (if I've understood correctly) is where we ended up after the past two discussions.
Changes:
- `type` (optional) represents the element type: `SINGLE` | `VEC2` | `VEC3` | `ARRAY` | ...
- `componentType` (required) represents the data type of the element's components: `UINT8` | `UINT16` | ...
- `componentCount` is defined only for fixed-length `ARRAY`
There was also some discussion of renaming the `type`/`componentType` properties, since most properties are single-component elements using only `componentType`. I have no objection to renaming but haven't attempted it in this PR; the current terms map pretty closely to glTF terminology. If we did want to rename, here's a straw man suggestion:
- `type` → …
> EXT_feature_metadata: Resolve 'type' / 'componentType' overlap, support VECN/MATN types

- extensions/2.0/Vendor/EXT_feature_metadata/README.md
- extensions/2.0/Vendor/EXT_feature_metadata/schema/class.property.schema.json
From discussion in https://github.com/CesiumGS/glTF/pull/8. 
Changes:
- Feature ID attributes and textures may specify values outside `[0, count - 1]` to indicate no feature is associated with the vertex, instance, or texel.
- Properties may specify a `noData` value ("sentinel value") to be treated as missing data.
- Removed `optional` and `default` from Property definition.
- Disallow `NaN`.
Questions:
- I don't think anything we've discussed allows nullable texels in feature property textures, ... that could be OK, since feature ID textures and a feature table could be used for these cases. Or do we need something like a `noData` texel value here?
- Note the particular language around variable-length arrays and `noData` values.
/cc @ptrgags @lilleyse
> EXT_feature_metadata: Allow null feature IDs and noData property values

- extensions/2.0/Vendor/EXT_feature_metadata/README.md
- extensions/2.0/Vendor/EXT_feature_metadata/schema/class.property.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/featureIdAttribute.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/featureIdTexture.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/gltf.EXT_feature_metadata.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/node.EXT_feature_metadata.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/primitive.EXT_feature_metadata.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/propertyTable.property.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/propertyTable.schema.json
- extensions/2.0/Vendor/EXT_feature_metadata/schema/propertyTexture.schema.json
Renames:
- `featureTable` → `propertyTable`
- `featureTexture` → `propertyTexture`
I've also attempted to use the term "properties" instead of "metadata" in a few cases, but may have a few more to clean up in the language/clarity pass.
We've discussed perhaps renaming the extension from `EXT_feature_metadata`. Also see https://github.com/CesiumGS/glTF/pull/4/#discussion_r588873765. The nearest extension in the glTF specification is [`EXT_mesh_gpu_instancing`](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_mesh_gpu_instancing), for reference. Ideas, in no particular order:
- `EXT_mesh_batching`
- `EXT_mesh_feature_batching`
- `EXT_mesh_properties`
- `EXT_feature_properties`
- `EXT_mesh_features`
- ... ?
If we do want to rename I'll do that update in a separate …
> EXT_feature_metadata: featureTables/featureTextures → propertyTables/propertyTextures

- extensions/2.0/Vendor/EXT_mesh_features/schema/class.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/propertyTable.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/propertyTexture.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/schema.schema.json
Changes:
- Restrict string IDs for classes, enums, and properties to alphanumeric and underscore characters
- Add "name" to feature tables and textures
Expectation here is that human-readable names may be provided in the "name" property if restrictions don't allow it in the string ID. In languages requiring non-ASCII characters it may be convenient to use IDs like `"property01"` and more meaningful names.
> EXT_feature_metadata: Restrictions on string IDs, add property table and texture names

- extensions/2.0/Vendor/EXT_mesh_features/schema/featureIdAttribute.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/gltf.EXT_mesh_features.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/primitive.EXT_mesh_features.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/propertyTable.schema.json
Changes:
- Fix schema for root `propertyTables` and `propertyTextures` (objects → arrays)
- Tighten schema for mutually exclusive properties, e.g. `offset` vs. `attribute`
- Update certain required properties
> EXT_mesh_features: Fixes and tightening of JSON schema.

- extensions/2.0/Vendor/EXT_mesh_features/README.md
[Direct link to extension](https://github.com/CesiumGS/glTF/tree/mesh-features-fix-links/extensions/2.0/Vendor/EXT_mesh_features)
* I noticed a couple broken links and fixed them
* Also noticed a missing changelog entry about the fact that the instancing metadata extension now lives in the node instead of the `EXT_mesh_gpu_instancing` extension
@donmccurdy could you review?
> Update broken links

- extensions/2.0/Vendor/EXT_mesh_features/README.md
When implementing these changes, we noticed that we forgot to add this to the changelog.
@donmccurdy could you review? are there any other restrictions to the property textures worth noting in the changelog?
> Add some missing entries to the changelog about property textures

- extensions/2.0/Vendor/EXT_feature_metadata/README.md
- extensions/2.0/Vendor/EXT_mesh_features/README.md
We recently merged some specs into the main branch of https://github.com/CesiumGS/3d-tiles, so update any links from that.
We also renamed Cesium 3D Metadata Specification to the 3D Metadata Specification. I updated link labels for this
@lilleyse could you review?
> Update links from 3d-tiles and handle renamed document

- extensions/2.0/Vendor/EXT_mesh_features/README.md
Updating EXT_mesh_features to include some of the phrasing feedback given on 3DTILES_metadata and Core Metadata.  Notably, trying to avoid using the term 'semantic' except when referencing a `property.semantic`.
> EXT_mesh_features: Wording cleanup.

- extensions/2.0/Vendor/EXT_mesh_features/README.md
- extensions/2.0/Vendor/EXT_mesh_features/schema/schema.schema.json
The inlined examples still referred to `type`, where `componentType` should be used
> Fixed inlined examples to use componentType

- extensions/2.0/Vendor/EXT_feature_metadata/README.md
- extensions/2.0/Vendor/EXT_feature_metadata/schema/mesh.primitive.EXT_feature_metadata.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/README.md
- extensions/2.0/Vendor/EXT_mesh_features/schema/mesh.primitive.EXT_mesh_features.schema.json
Using the full name `mesh.primitive` makes it easier to automatically extend core glTF's `mesh.primitive.schema.json`
> Change primitive to mesh.primitive in EXT_mesh_features and EXT_feature_metadata schemas

- extensions/2.0/Vendor/EXT_mesh_features/README.md
- extensions/2.0/Vendor/EXT_mesh_features/schema/propertyTexture.property.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/propertyTexture.schema.json
Items in the property texture `properties` dictionary are now objects instead of arrays of channels.
The reason for this change is to be able to add other properties like scale and offset for quantization, or extras/extensions. It's also more symmetric with property tables.
Before
```
"outsideTemperature": [1]
// nowhere to put other properties
```
After
```
"outsideTemperature": {
"channels": [1],
"scale": 0.1,
"offset": 10.0
}
```
> Property texture properties as objects

- extensions/2.0/Vendor/EXT_instance_features/README.md
- extensions/2.0/Vendor/EXT_instance_features/schema/featureId.schema.json
- extensions/2.0/Vendor/EXT_instance_features/schema/featureIdAttribute..schema.json
- extensions/2.0/Vendor/EXT_instance_features/schema/featureIdInstanceAttibute..schema.json
- extensions/2.0/Vendor/EXT_instance_features/schema/node.EXT_instance_features.schema.json
Derived from the [original EXT_mesh_features state](https://github.com/CesiumGS/glTF/tree/e8b8a1065ac9e3db571fa8af836fac5480020228/extensions/2.0/Vendor/EXT_mesh_features).
That typo in the commit message will haunt my forever. But here we go, the preview is at https://github.com/javagl/glTF/tree/ext-mesh-features-revision-instance-features/extensions/2.0/Vendor/EXT_instance_features 
The text originally said
> Feature IDs may be assigned to individual GPU instances using an instance attribute, or generated implicitly by instance index. 
It is not yet decided how this "implicit generation by index" should be accomplished. (Just omitting the `attribute` will not be compliant with the `featureId` schema)
> Add EXT_instance_features extension

- extensions/2.0/Vendor/EXT_structural_metadata/schema/class.property.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/propertyAttribute.property.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/propertyTable.property.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/propertyTexture.property.schema.json
Based on the changes in the 3D Metadata Specification from https://github.com/CesiumGS/3d-tiles/pull/640 , the descriptions in the schema have been updated.
> Update descriptions of offset/scale/min/max in schema

- extensions/2.0/Vendor/EXT_instance_features/README.md
- extensions/2.0/Vendor/EXT_instance_features/schema/featureId.schema.json
- extensions/2.0/Vendor/EXT_instance_features/schema/node.EXT_instance_features.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/README.md
- extensions/2.0/Vendor/EXT_mesh_features/schema/featureId.schema.json
- extensions/2.0/Vendor/EXT_mesh_features/schema/mesh.primitive.EXT_mesh_features.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/README.md
- extensions/2.0/Vendor/EXT_structural_metadata/schema/class.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/schema.schema.json
One of the recent changes in `EXT_mesh_features` was to use a dictionary instead of an array for the `featureIds` property which enforces the usage of set IDs. There were some downsides to this:
* For basic usage a set ID may be not be needed, adding extra complexity and possibly confusion
* It was a breaking change for the older version of `EXT_mesh_features`
* Implementation churn
With `featureIds` as an array again, a new optional property is added called `label` which allows you to identify feature ID sets across different glTF primitives, or across different glTF assets such as in 3D Tiles.
Also added a regex to enforce proper naming of the label.
> Change featureIds dictionary back to array

- extensions/2.0/Vendor/EXT_structural_metadata/schema/EXT_structural_metadata.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/mesh.primitive.EXT_structural_metadata.schema.json
The references to property tables and property textures should use `glTFid` instead of `integer`.
Together with https://github.com/CesiumGS/glTF/pull/66 , this fixes https://github.com/CesiumGS/3d-tiles/issues/751
> Replace integer with glTFid

- extensions/2.0/Vendor/EXT_mesh_features/schema/featureId.schema.json
The `propertyTable` of a feature ID should be a `glTFid`, and not a plain `integer` ( https://github.com/CesiumGS/3d-tiles/issues/751 )
> Change integer to glTFid

- extensions/2.0/Vendor/EXT_structural_metadata/README.md
- extensions/2.0/Vendor/EXT_structural_metadata/schema/EXT_structural_metadata.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/glTF.EXT_structural_metadata.schema.json
Metadata assigned to glTF objects - like nodes and materials - is now encoded in JSON rather than in binary in a property table. This is similar to tileset and tile metadata in 3D Tiles. This is a breaking change that shouldn't have a wide impact.
> `EXT_structural_metadata` - JSON encoding

- extensions/2.0/Vendor/EXT_structural_metadata/README.md
- extensions/2.0/Vendor/EXT_structural_metadata/schema/EXT_structural_metadata.schema.json
- extensions/2.0/Vendor/EXT_structural_metadata/schema/glTF.EXT_structural_metadata.schema.json
Bringing in the recent updates to `EXT_structural_metadata` from https://github.com/CesiumGS/glTF/pull/71
> Update EXT_structural_metadata in cesium-native branch

- extensions/2.0/Vendor/EXT_structural_metadata/schema/class.schema.json
https://github.com/CesiumGS/glTF/pull/70 proposes adding a `parent` property to a class. Even though this change isn't official yet we're already using it internally in the design tiler and would like to include it in cesium-native's generated code.
> Add parent class to cesium-native branch

- extensions/2.0/Khronos/KHR_spz_gaussian_splats_compression/README.md
@weegeekps This PR is a proposal to allow for uncompressed attributes outside of the SPZ compressed payload. This change is needed to support Gaussian Splats feature attribution where additional vertex attribute(s) (i.e. FEATURE_INDEX_i ) are required but are not supported in the SPZ format.
> Allow for non-SPZ encoded vertex attributes
